files: '.py|.json'
exclude: '.git'
default_stages: [pre-commit]

repos:
  - repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
      - id: black

#  - repo: https://github.com/timothycrosley/isort
#    rev: 5.13.2
#    hooks:
#      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-json
        files: '.json'

  - repo: https://github.com/lk16/detect-missing-init
    rev: v0.1.6
    hooks:
    - id: detect-missing-init
      args: ['--create', "--track", "--python-folders", "tests,PySDM,examples/PySDM_examples"]

  - repo: https://github.com/AgnieszkaZaba/devops_tests
    rev: badges-hook
    hooks:
      - id: check-notebook-open-atmos-structure
        name: check notebook has open-atmos structure
        args: [--repo-name=PySDM]
