# just defaults
language: python
python: 3.7
os: linux

jobs:
  include:
    - name: "Python 3.7 on Linux numba::parallel=False"
      before_script:
        - sed -i s/parallel=True/parallel=False/g PySDM/backends/numba/conf.py
        - sed -i 's/"rU"/"r"/g' /home/travis/virtualenv/python3.7.1/lib/python3.7/site.py
      after_success:
        - codecov
    - name: "Python 3.7 on Linux numba::parallel=True"
      before_script:
        - sed -i s/parallel=False/parallel=True/g PySDM/backends/numba/conf.py
        - sed -i 's/"rU"/"r"/g' /home/travis/virtualenv/python3.7.1/lib/python3.7/site.py
    - name: "Python 3.7 on OSX"
      language: shell
      os: osx
      osx_image: xcode11.3
      before_install:
        - export PY_SFX=3
    - name: "Python 3.7 on Windows"
      language: shell
      os: windows
      before_install:
        - choco install python --version 3.7
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip$PY_SFX install -U pytest-cov codecov setuptools>=50.3.2
  - |
    # https://stackoverflow.com/questions/55486248/deprecationwarning-in-python-3-6-and-3-7-with-pillow-distutils-imp
    if [[ $TRAVIS_OS_NAME == linux ]]; then
      python$PY_SFX $PY_FLAGS -c 'import os, virtualenv; virtualenv.install_distutils(os.environ["VIRTUAL_ENV"])' || exit 1
    fi;
  - pip$PY_SFX install -U -r test-time-requirements.txt
  - pip$PY_SFX install -e .
  - export PY_FLAGS="-We"

script:
  - PYTEST="python$PY_SFX -m pytest $PY_FLAGS -p no:unraisableexception"
  - NUMBA_DISABLE_JIT=1 $PYTEST PySDM_tests/unit_tests --cov-report term --cov=PySDM
  - $PYTEST
