# just defaults
language: python
python: 3.7
os: linux

jobs:
  include:
    - name: "Python 3.8 with newest packages on Linux"
      os: linux
      language: python
      python: "3.8"
      before_install:
        - sudo `which pip` install --upgrade pip
      before_script:
        - pip install -U $(cat requirements.txt | awk -F '==|>=' {'print $1'})
    - name: "Python 3.7 on Linux numba::parallel=False"
      before_script:
        - sed -i s/parallel=True/parallel=False/g PySDM/backends/numba/conf.py
      after_success:
        - codecov
    - name: "Python 3.7 on Linux numba::parallel=True"
      before_script:
        - sed -i s/parallel=False/parallel=True/g PySDM/backends/numba/conf.py
    - name: "Python 3.7 on OSX"
      language: shell
      os: osx
      before_install:
        - export PY_SFX=3
    - name: "Python 3.7 on Windows"
      language: shell
      os: windows
      before_install:
        - choco install python --version 3.7
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip$PY_SFX install -U ipykernel pytest pytest-cov codecov nbconvert jupyter_client
  - pip$PY_SFX install -U -r requirements.txt

script:
  - NBCONVERT="jupyter nbconvert --to markdown --stdout"
  - NUMBA_DISABLE_JIT=1 python$PY_SFX -m pytest PySDM_tests/unit_tests --cov-report term --cov=PySDM
  - python$PY_SFX -m pytest
  - |
      python$PY_SFX -m ipykernel install --user
      for i in PySDM_examples/*/demo.ipynb; do
         $NBCONVERT $i > $i.md.repo;
         $NBCONVERT --execute --ExecutePreprocessor.timeout=1800 $i || exit 1;
      done;
      for i in PySDM_tutorials/*/*.ipynb; do
         $NBCONVERT $i > $i.md.repo;
         $NBCONVERT --execute $i > $i.md.travis || exit 1;
         diff --ignore-all-space $i.md.repo $i.md.travis
      done;
  - |
      if [[ $TRAVIS_OS_NAME == linux ]]; then
        for i in PySDM_examples/*/example*.py; do
          echo $i
          PYTHONPATH=. travis_wait 15 python$PY_SFX $i || exit 1
        done;
      fi;
  # execute Python lines from README.md
  - awk < README.md 'BEGIN {cmt=1; swp=0;} {swp=(substr($0,1,3)=="```"); if (swp && !cmt) {cmt=1; swp=0} if (cmt) print("#" $0); else print $0; if (swp && cmt) {cmt=0; swp=0}}' | python$PY_SFX
